if(EXISTS "/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/unit/stcpp_test_unit_risk[1]_tests.cmake")
  include("/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/unit/stcpp_test_unit_risk[1]_tests.cmake")
else()
  add_test(stcpp_test_unit_risk_NOT_BUILT stcpp_test_unit_risk_NOT_BUILT)
endif()
