if(EXISTS "/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/unit/test_risk_gateway[1]_tests.cmake")
  include("/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/unit/test_risk_gateway[1]_tests.cmake")
else()
  add_test(test_risk_gateway_NOT_BUILT test_risk_gateway_NOT_BUILT)
endif()
