if(EXISTS "/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/unit/test_wal_writer[1]_tests.cmake")
  include("/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/unit/test_wal_writer[1]_tests.cmake")
else()
  add_test(test_wal_writer_NOT_BUILT test_wal_writer_NOT_BUILT)
endif()
