if(EXISTS "/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/unit/test_position_ledger[1]_tests.cmake")
  include("/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/unit/test_position_ledger[1]_tests.cmake")
else()
  add_test(test_position_ledger_NOT_BUILT test_position_ledger_NOT_BUILT)
endif()
