if(EXISTS "/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/unit/test_spsc_queue[1]_tests.cmake")
  include("/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/unit/test_spsc_queue[1]_tests.cmake")
else()
  add_test(test_spsc_queue_NOT_BUILT test_spsc_queue_NOT_BUILT)
endif()
