if(EXISTS "/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/unit/test_paper_signer[1]_tests.cmake")
  include("/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/unit/test_paper_signer[1]_tests.cmake")
else()
  add_test(test_paper_signer_NOT_BUILT test_paper_signer_NOT_BUILT)
endif()
