if(EXISTS "/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/integration/stcpp_test_integration_r11_pollution[1]_tests.cmake")
  include("/Users/wangweibo/code/sports-trader-cpp/build_adr010/tests/integration/stcpp_test_integration_r11_pollution[1]_tests.cmake")
else()
  add_test(stcpp_test_integration_r11_pollution_NOT_BUILT stcpp_test_integration_r11_pollution_NOT_BUILT)
endif()
